import NavBar from "./components/NavBar";
import "./globals.css";

export const metadata = {
  title: "openTable",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="bg-gray-100 min-h-screen w-screen">
          <main className="max-w-screen-2xl m-auto bg-white">
            <NavBar />
            {children}
          </main>
        </main>
      </body>
    </html>
  );
}
//050e197b2e480da31820d8d34c7ae7f5ffc69ad4
